
fig_dir = '~/work/wikisim/figs';

%% partial correlations within ROIs

% path to results from within-subject partial correlation
% permutation results for each ROI
rsa_dir = '~/work/bender/batch/rsa';
wsubjnos = [1 2 4 5 6 7 8 10 11 12 13 14 15 16 17 18 19 20 21 22 23 ...
            24 25 26 28 29 31 32 34 35 36 37 38];
models = {'hmax' 'subcat' 'wiki_w2v'};

% functional rois
face_rois = {'r_ofa' 'b_ffa' 'b_pat'};
face_roi_names = {'OFA' 'FFA' 'ATFA'};
scene_rois = {'b_opa' 'b_rsc' 'b_ppa'};
scene_roi_names = {'OPA' 'RSC' 'PPA'};

% faces
fprintf('Face ROIs, face items:\n')
mat = plot_roi_model(rsa_dir, models, 'face', ...
                     face_rois, face_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'face_rois_face.eps'));
mat = plot_roi_model(rsa_dir, models, 'face', ...
                     scene_rois, scene_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'scene_rois_face.eps'));

% scenes
fprintf('Scene ROIs, scene items:\n')
mat = plot_roi_model(rsa_dir, models, 'scene', ...
                     scene_rois, scene_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'scene_rois_scene.eps'));
mat = plot_roi_model(rsa_dir, models, 'scene', ...
                     face_rois, face_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'face_rois_scene.eps'));

mat = plot_roi_model(rsa_dir, {'geo'}, 'scene', ...
                     scene_rois, scene_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'scene_rois_geo.eps'));
mat = plot_roi_model(rsa_dir, {'geo'}, 'scene', ...
                     face_rois, face_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'face_rois_geo.eps'));

mat = plot_roi_model(rsa_dir, [models {'geo'}], 'scene', ...
                     {'b_hip_fshs'}, {'HPC'}, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'hpc_scene.eps'));
mat = plot_roi_model(rsa_dir, models, 'face', ...
                     {'b_hip_fshs'}, {'HPC'}, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'hpc_face.eps'));

mtl_rois = {'b_phc_jl_mni' 'b_prc_jl_mni' 'b_erc_jl_mni' 'b_hip_fshs'};
mtl_roi_names = {'PHC' 'PRC' 'ERC' 'HPC'};
mat = plot_roi_model(rsa_dir, models, 'face', ...
                     mtl_rois, mtl_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'mtl_rois_face.eps'));
mat = plot_roi_model(rsa_dir, models, 'scene', ...
                     mtl_rois, mtl_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'mtl_rois_scene.eps'));
mat = plot_roi_model(rsa_dir, {'geo'}, 'scene', ...
                     mtl_rois, mtl_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'mtl_rois_geo.eps'));

hip_rois = {'hip_y0' 'hip_y1' 'hip_y2'};
hip_roi_names = {'tail' 'body' 'head'};
mat = plot_roi_model(rsa_dir, models, 'face', ...
                     hip_rois, hip_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'hip_rois_face.eps'));
mat = plot_roi_model(rsa_dir, models, 'scene', ...
                     hip_rois, hip_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'hip_rois_scene.eps'));
mat = plot_roi_model(rsa_dir, {'geo'}, 'scene', ...
                     hip_rois, hip_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'hip_rois_geo.eps'));

mtlc_rois = {'phc_y0' 'phc_y1' 'prc_y0' 'prc_y1' 'prc_y2'};
mtlc_roi_names = {'pPHC' 'aPHC' 'pPRC' 'mPRC' 'aPRC'};
mat = plot_roi_model(rsa_dir, models, 'face', ...
                     mtlc_rois, mtlc_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'mtlc_rois_face.eps'));
mat = plot_roi_model(rsa_dir, models, 'scene', ...
                     mtlc_rois, mtlc_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'mtlc_rois_scene.eps'));
mat = plot_roi_model(rsa_dir, {'geo'}, 'scene', ...
                     mtlc_rois, mtlc_roi_names, wsubjnos, ...
                     fullfile(fig_dir, 'loc_rois', 'mtlc_rois_geo.eps'));

